### ISSUE TITLE
Alma Linux - font not found (suggestion)

### ISSUE THREAD

**Issue by TudorHulban** [mandolyte/mdtopdf#63] opened 2024-12-19 09:15 UTC
hi,
tried to use on alma linux, but getting:
```sh
md2pdf -i 02_Works_Events.md -o 02_Works_Events.pdf
error:error on 02_Works_Events.pdf:could not locate "helveticabb" among embedded core font definition files
```
guess what is important is to render something with existing system fonts. maybe you could introduce:  
a. checking dependencies before document  processing
b. the capability of working with the fonts that exist on the system

```sh
cat /etc/os-release 
NAME="AlmaLinux"
VERSION="9.5 (Teal Serval)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.5 (Teal Serval)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.5"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
SUPPORT_END=2032-06-01
```
no helvetica:

```sh
dnf search helvetica*
AlmaLinux 9 - AppStream                         6.2 MB/s | 9.6 MB     00:01    
AlmaLinux 9 - BaseOS                            5.1 MB/s | 5.7 MB     00:01    
AlmaLinux 9 - CRB                               3.0 MB/s | 2.9 MB     00:00    
AlmaLinux 9 - Extras                             22 kB/s |  13 kB     00:00    
Brave Browser                                   361 kB/s | 132 kB     00:00    
Docker CE Stable - x86_64                       212 kB/s |  61 kB     00:00    
Extra Packages for Enterprise Linux 9 - x86_64   13 MB/s |  23 MB     00:01    
Extra Packages for Enterprise Linux 9 openh264  2.0 kB/s | 2.5 kB     00:01    
google-chrome                                    11 kB/s | 4.4 kB     00:00    
Hashicorp Stable - x86_64                       3.5 MB/s | 1.6 MB     00:00    
RPM Fusion for EL 9 - Free - Updates            282 kB/s | 220 kB     00:00    
RPM Fusion for EL 9 - Nonfree - Updates         121 kB/s |  91 kB     00:00    
Visual Studio Code                              9.2 MB/s | 6.7 MB     00:00    
No matches found.
```

**Comment by jessp01** [comment] 2024-12-19 21:03
Hello @TudorHulban ,

I'm a bit confused about the Helvetica reference because it's nowhere in the code (other than the README and usage message; to illustrate specifying a font with `--font-name` and `--font-file`).

I've also tested on Rocky 9 myself:
```
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Rocky
Description:	Rocky Linux release 9.4 (Blue Onyx)
Release:	9.4
Codename:	BlueOnyx
```
with the latest release (2.2.5) and was unable to reproduce this issue.

What version of `md2pdf` are you using and is it possible that you've used additional arguments in your command which you've not included when submitting this issue?

By the way `dnf search helvetica*` will only yield results if there are packages whose name includes the substring "helvetica". What you really want in such a case is `dnf whatprovides "/*helvetica*"` ; it does not matter in this particular case as there no packages in the official Rocky (or RHEL for that matter) repos that provide this font but still, for general edification:)

**Comment by jessp01** [comment] 2024-12-26 14:41
Closing for now but feel free to reopen with more info.

**Closed by jessp01** 2024-12-26 14:41 UTC
